### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tatsuya9156** [Tatsuya9156/furima-33498#9]
# URL
https://furima-33498.herokuapp.com/

# Basic認証のIDとパスワード
user：hamamoto
pass：9156

# 出品者用のメールアドレスとパスワード
メールアドレス：test1@example
パスワード：test11

# 購入者用のメールアドレスとパスワード
メールアドレス：test2@example
パスワード：test22

# 購入用カードの番号・期限・セキュリティコード
※とりあえずいつも入力してるやつです。
番号：4242424242424242
期限：12 / 28
セキュリティコード：123

**Comment by kaho0919** [comment]
ご提出ありがとうございます‼︎

問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉


着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
